image: "continuumio/miniconda3"

before_script:
  - python --version
  - conda update conda
  - conda env create -f environment.yml
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"

stages:
  - Static Analysis
  - Tests

flake8:
  stage: Static Analysis
  script:
  - flake8 src/
  - flake8 tests/

isort:
  stage: Static Analysis
  script:
  - isort --check-only src/

safety:
  stage: Tests
  script:
    - safety check

doc:
  stage: Static Analysis
  script:
  - make doc
  allow_failure: true


# normally no need to use black formatting because when saving black is applied
# black:
#   stage: Static Analysis
#   script:
#   - black src/application/evaluate.py

unit_test:
  stage: Tests
  script:
  - coverage run --source=src/ -m unittest discover -s tests/
  - coverage report

