img_height: 224
img_width: 224
img_n_channels: 3
transfer_learning: True
n_epochs: 2
learning_rate: 0.0001
batch_size: 1
fine_tuning: True
fine_tuning_epochs: 1
fine_tuning_lr: 0.00001
test_mode: 1
dataset: "food-101_224_224/"
resize: True
augment: True
aug_factor: 2
weights: "efficientnetb0/best_model.h5"
