img_height: 380
img_width: 380
img_n_channels: 3
transfer_learning: False
n_epochs: 50
learning_rate: 0.0001
batch_size: 16
fine_tuning: True
fine_tuning_epochs: 50
fine_tuning_lr: 0.00001
test_mode: 1
dataset: "food-101"
weights: "efficientnetb4/best_model.h5"
